doodle:
  usepad: true
  internalPadUrl: "http://localhost:9001/"
  externalPadUrl: "http://localhost:9001/"
  padApiKey: "19d89ca52bc0fa4f19d6325464d9d7a032649b9fa68c111514627081e2784b4a"
  organizermail: "rakotomanana.haga@gmail.com"
  tmpfolder: "/tmp/excelFiles"
